/*
 * EXI_config.h
 *
 *  Created on: ??þ/??þ/????
 *      Author: ÇáÝÇãÕÑ
 */

#ifndef MCAL_EXTI_HEADER_EXTI_CONFIG_H_
#define MCAL_EXTI_HEADER_EXTI_CONFIG_H_

/* CONFIGURE EXTI 0
   1- EXTI_LOW_LEVEL
   2- EXTI_ANY_LOGICAL_CHANGE
   3- EXTI_FALLING_EDGE
   4- EXTI_RISING_EDGE          */

 #define EXTI0_SENSE_CONTROL    EXTI_FALLING_EDGE

/* CONFIGURE EXTI 1
   1- EXTI_LOW_LEVEL
   2- EXTI_ANY_LOGICAL_CHANGE
   3- EXTI_FALLING_EDGE
   4- EXTI_RISING_EDGE          */


 #define EXTI1_SENSE_CONTROL    EXTI_ANY_LOGICAL_CHANGE


/* CONFIGURE EXTI 1
   1- EXTI_INT2_FALLING_EDGE
   2- EXTI_INT2_RISING_EDGE        */


#define  EXTI2_SENSE_CONTROL    EXI_INT2_rising_edge

/* CONFIGURE ENABLE STATE
 * 1- EXTI_ENABLE_STATE
 * 2- EXTI_DISABLE_STATE        */

#define EXTI_INT0_STATE    EXTI_ENABLE_STATE
#define EXTI_INT1_STATE    EXTI_DISABLE_STATE
#define EXTI_INT2_STATE    EXTI_DISABLE_STATE


#endif /* MCAL_EXTI_HEADER_EXTI_CONFIG_H_ */
