
#ifndef UART_CONFIG_H_
#define UART_CONFIG_H_

#define UART_DATA_BITS				UART_DATA_BITS_8
#define UART_MODE					UART_MODE_ASYNCHRONOUS
#define UART_BAUD_RATE				9600UL
#define UART_PARITY_MODE			UART_PARITY_NO
#define UART_STOP_BITS				UART_STOP_BITS_1

#define UART_INTERRUPT_STATE_RXC	UART_DISABLE
#define UART_INTERRUPT_STATE_TXC	UART_DISABLE
#define UART_INTERRUPT_STATE_UDRE	UART_DISABLE

#define UART_TRANSMIT_ENABLE		UART_ENABLE
#define UART_RECEIVE_ENABLE			UART_ENABLE



#endif /* UART_CONFIG_H_ */
